### ISSUE TITLE
Issue scripts/train/baseline_local.py

### ISSUE THREAD

**Issue by jayl940712** [panjingyu/Decentralized-Routability-Estimation#2]
Hi,

There seems to be a typo: 

scripts/train/baseline_local.py, line 56

The client_ckpt seems not to be defined properly.

Best

**Comment by jayl940712** [comment]
Also in 

scripts/dataset/preprocess_data.py, line 124

Is there a reason clients[:-1] is used? Using the default design setup, I see that client_9 is not processed.

Thanks.

**Comment by panjingyu** [comment]
Thanks for pointing out the typo! It is now fixed in [1af1be8](https://github.com/panjingyu/Decentralized-Routability-Estimation/commit/1af1be8cf22255ef7dae7abe80b60b329f93454f).

Regarding line 124 in scripts/dataset/preprocess_data.py, please feel free to remove `[:-1]`. I used this list slicing because I was trying to run preprocessing of `clients[:-1]` on GPU and that of `clients[-1]` on CPU. OOM issues occurred when preprocessing the last client on my GPU. Sorry for the confusion!

**Comment by mjm65688** [comment]
> Also in
> 
> scripts/dataset/preprocess_data.py, line 124
> 
> Is there a reason clients[:-1] is used? Using the default design setup, I see that client_9 is not processed.
> 
> Thanks.

Hello，I had some questions about implementation of this project. Could you add my contact information(wechat:mjm65688) for communication? Thanks.
